const INIT = 'INIT';
const UPDATE_ASSIGNEE = 'UPDATE_ASSIGNEE';
const UPDATE_LABEL = 'UPDATE_LABEL';
const UPDATE_MILESTONE = 'UPDATE_MILESTONE';

export { INIT, UPDATE_ASSIGNEE, UPDATE_LABEL, UPDATE_MILESTONE };
